# basic options
title: Vakantie Maart 2019 - Lanzarote
author: Kees
description: Blog van de vakantie van Maart 2019
URL: "https://github.com/Prudento-NL/2019-03-vakantie-lanzarote.git"

images: "https://prudento-nl.github.io/2019-03-vakantie-lanzarote/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
