# basic options
title: Vakantie Maart 2019 - Lanzarote
author: Kees
description: Blog van de vakantie van Maart 2019
baseurl: "/2019-03-lanzarote" 
url: "https://prudento-nl.github.io" 

images: "https://prudento-nl.github.io/2019-03-lanzarote/images"

# Build settings
markdown: kramdown
theme: minima

minima:
  date_format: "%d-%m-%Y"
